ARGUMENT_FLOW_NAME = 'flow_name'
ARGUMENT_STEP_NAME = 'step_name'
ARGUMENT_RUN_MODE = 'run_mode'
RUN_MODE_RECOVERY = 'run_mode_recovery'
RUN_MODE_ONE_STEP = 'run_mode_one_step'
RUN_MODE_RUN_FROM = 'run_mode_run_from'
RUN_MODE_NOMINAL = 'run_mode_nominal'
